const pkg = require('./package.json');

module.exports = {
    version: '>=0.10.0',
    type: 'library',
    name: 'proto-ui',
    CamelName: 'ProtoUI',
    docs: {
        title: 'Proto UI Component Library',
        logo: 'Prototype component',
        mode: 'history',
        base: '/proto-ui/',
        github: 'https://github.com/saashqdev/proto-ui#next',
        package: pkg,
        navbar: [
            { text: 'Components', to: '/components' },
            { text: 'Commands and tools', to: '/misc' },
            { text: 'Layout', to: '/layouts' },
        ],
        components: [
            { group: 'Guide', name: 'quickstart', title: 'Quick Start', path: './docs/views/guide/quickstart.md' },
            { group: 'Guide', name: 'pattern', title: 'Design Pattern', path: './docs/views/guide/pattern.md' },
            { group: 'Guide', name: 'changelog', title: 'Update log', href: 'https://github.com/saashqdev/proto-ui/releases', target: '_blank' },
            { group: 'Guide', name: 'theme', title: 'Theme', path: 'library/styles/theme.md' },
            { group: 'Basic', name: 'typography', title: 'Typography', path: 'library/styles/typography.md' },
            { group: 'Basic', name: 'u-text', title: 'Text' },
            { group: 'Basic', name: 'u-link', title: 'Link' },
            { group: 'Basic', name: 'u-button', title: 'Button' },
            { group: 'Basic', name: 'u-label', title: 'Label' },
            { group: 'Basic', name: 'u-badge', title: 'Badge' },
            { group: 'Basic', name: 'u-avatar', title: 'Avatar' },
            { group: 'Basic', name: 'i-icon', title: 'Icon' },
            { group: 'Basic', name: 'u-logo', title: 'Logo' },
            { group: 'Layout', name: 'u-linear-layout', title: 'Linear Layout' },
            { group: 'Layout', name: 'u-grid-layout', title: 'Grid Layout' },
            { group: 'Layout', name: 'u-list', title: '列表' },
            // { group: 'Layout', name: 'u-desc-list', title: 'Description List' },
            // { group: 'Layout', name: 'u-info-list', title: 'Information List' },
            { group: 'Layout', name: 'u-table', title: 'Table' },
            { group: 'Layout', name: 'u-form-table', title: 'Form Table' },
            { group: 'Layout', name: 'u-article', title: 'Article' },
            { group: 'Layout', name: 'u-collapse', title: 'Folding Panel' },
            { group: 'Navigation', name: 'u-navbar', title: 'Navigation Bar' },
            { group: 'Navigation', name: 'u-sidebar', title: 'Sidebar' },
            { group: 'Navigation', name: 'u-menu', title: 'Menu' },
            { group: 'Navigation', name: 'u-tabs', title: 'Tab Page' },
            { group: 'Navigation', name: 'u-steps', title: 'Step Bar' },
            { group: 'Navigation', name: 'u-crumb', title: 'Breadcrumbs' },
            { group: 'Navigation', name: 'u-pagination', title: 'Page Turner' },
            { group: 'Navigation', name: 'u-combo-pagination', title: 'Combined page turner' },
            { group: 'Form', name: 'u-form', title: 'Form' },
            { group: 'Form', name: 'u-validator', title: 'Validator' },
            { group: 'Form', name: 'u-input', title: 'Single-Line Input' },
            { group: 'Form', name: 'u-number-input', title: 'Number Input' },
            { group: 'Form', name: 'u-textarea', title: 'Multi-Line Input' },
            { group: 'Form', name: 'u-radios', title: 'Radio Group' },
            { group: 'Form', name: 'u-checkboxes', title: 'Multiple Selection Group' },
            { group: 'Form', name: 'u-switch', title: 'Switch' },
            { group: 'Form', name: 'u-select', title: 'Selection Box' },
            { group: 'Form', name: 'u-cascade-select', title: 'Cascade Selection' },
            { group: 'Form', name: 'u-region-select', title: 'Region Selection' },
            { group: 'Form', name: 'u-slider', title: 'Slider' },
            { group: 'Form', name: 'u-combo-slider', title: 'Combined Slider' },
            { group: 'Form', name: 'u-uploader', title: 'File Upload' },
            { group: 'Form', name: 'u-form-table-view', title: 'Form Table View' },
            { group: 'Data', name: 'u-list-view', title: 'List Selection' },
            { group: 'Data', name: 'u-tree-view', title: 'Tree Selection' },
            { group: 'Data', name: 'u-table-view', title: 'Table View' },
            { group: 'Data', name: 'u-transfer', title: 'Shuttle Box' },
            // { group: 'DateTime', name: 'u-calendar', title: 'Calendar' },
            // { group: 'DateTime', name: 'u-date-picker', title: 'Date Selection' },
            // { group: 'DateTime', name: 'u-time-picker', title: 'Time Selection' },
            // { group: 'DateTime', name: 'u-date-time-picker', title: 'Date Time' },
            { group: 'Popper', name: 'm-popper', title: 'Pop-up layer' },
            { group: 'Popper', name: 'u-popup', title: 'Pop-up box' },
            { group: 'Popper', name: 'u-tooltip', title: 'Tooltip' },
            { group: 'Popper', name: 'u-icon-tooltip', title: 'Icon tooltip' },
            { group: 'Feedback', name: 'u-spinner', title: 'Loading icon' },
            { group: 'Feedback', name: 'u-loading', title: 'Loading' },
            { group: 'Feedback', name: 'u-toast', title: 'Toast prompt' },
            { group: 'Feedback', name: 'u-modal', title: 'Modal' },
            { group: 'Feedback', name: 'u-drawer', title: 'Drawer' },
            // { group: 'Feedback', name: 'u-lightbox', title: 'Lightbox' },
            { group: 'Effects', name: 'u-carousel', title: 'Carousel' },
            { group: 'Effects', name: 'e-ripple', title: 'Ripple' },
            { group: 'Effects', name: 'e-watermark', title: 'Watermark' },
            { group: 'Progress & Charts', name: 'u-linear-progress', title: 'Linear Progress Bar' },
            { group: 'Progress & Charts', name: 'u-circular-progress', title: 'Circular Progress Bar' },
            { group: 'Mixins & Functional', name: 'm-dynamic', title: 'Dynamic List' },
            { group: 'Mixins & Functional', name: 'm-emitter', title: 'Emitter' },
            { group: 'Mixins & Functional', name: 'm-pub-sub', title: 'Publish and Subscribe' },
            { group: 'Mixins & Functional', name: 'm-parent', title: 'Parent-Child Mode' },
            { group: 'Mixins & Functional', name: 'm-group', title: 'Grouping Mode' },
            { group: 'Mixins & Functional', name: 'm-root', title: 'Root Node Mode' },
            { group: 'Mixins & Functional', name: 'm-singlex', title: 'Single Selection Mode' },
            { group: 'Mixins & Functional', name: 'm-multiplex', title: 'Multiple Selection Mode' },
            { group: 'Mixins & Functional', name: 'm-complex', title: 'Compound Mode' },
            { group: 'Mixins & Functional', name: 'f-collapse-transition', title: 'Folding Transition' },
            { group: 'Mixins & Functional', name: 'f-draggable', title: 'Draggable' },
            { group: 'Mixins & Functional', name: 'f-droppable', title: 'Droppable' },
            { group: 'Mixins & Functional', name: 'f-dragger', title: 'Dragger' },
            { group: 'Mixins & Functional', name: 'f-render', title: 'Renderer' },
            { group: 'Mixins & Functional', name: 'f-slot', title: 'Quick Slot' },
            { group: 'Mixins & Functional', name: 'f-forbidden', title: 'Forbidden' },
        ],
        blocks: [],
        directives: [
            { group: 'Directives', name: 'v-repeat-click', title: 'Repeat Click' },
            // { group: 'Directives', name: 'v-click-outside' },
            { group: 'Directives', name: 'v-ellipsis-title', title: 'Text Ellipsis Prompt' },
            { group: 'Directives', name: 'v-focus', title: 'Automatically Get Focus' },
        ],
        filters: [],
        utils: [
            // { group: 'Utils', name: 'DataSource', title: 'Data Source' },
            // { group: 'Utils', name: 'Formatters', title: 'Formatter' },
            { group: 'Utils', name: 'dom', title: 'DOM Related' },
            { group: 'Utils', name: 'edit', title: 'Edit Related' },
        ],
        layouts: [
            { group: 'Scene', name: 'l-dashboard', title: 'Dashboard Layout' },
            { group: 'Scene', name: 'l-document', title: 'Document Layout' },
            { group: 'Scene', name: 'l-page', title: 'General Page Layout' },
            { group: 'Scene', name: 'l-side-main', title: 'Left Column Fixed Layout' },
            { group: 'Router', name: 'l-wrapper', title: 'Transparent Page' },
        ],
    },
};